//
//  GlobalMacro.swift
//  BehanceDaily
//
//  Created by chenkai on 2017/4/7.
//  Copyright © 2017年 chenkai. All rights reserved.
//

let BEHANCE_APP_KEY = "n3g6aFKqxwXwLbrDu9xl3FEPusk8QLXi"
let BEHANCE_URL = "https://api.behance.net/v2"

let BEHANCE_ARGUMENT_CLIENT_ID = "client_id"
let BEHANCE_ARGUMENT_SEARCH_PROJECT_Q = "q"
let BEHANCE_ARGUMENT_SEARCH_PROJECT_SORT = "sort"
let BEHANCE_ARGUMENT_SEARCH_PROJECT_TIME = "time"
let BEHANCE_ARGUMENT_SEARCH_PROJECT_FIELD = "field"
let BEHANCE_ARGUMENT_SEARCH_PROJECT_COUNTRY = "country"
let BEHANCE_ARGUMENT_SEARCH_PROJECT_STATE = "state"
let BEHANCE_ARGUMENT_SEARCH_PROJECT_CITY = "city"
let BEHANCE_ARGUMENT_SEARCH_PROJECT_PAGE = "page"
let BEHACNE_ARGUMENT_SEARCH_PROJECT_TAGS = "tags"
let BEHANCE_ARGUMENT_SEARCH_PROJECT_COLOR_HEX = "color_hex"
let BEHANCE_ARGUMENT_SEARCH_PROJECT_COLOR_RANGE = "color_range"
let BEHANCE_ARGUMENT_SEARCH_PROJECT_COLOR_LICESE = "license"



let BEHANCE_URL_CATEGORY = "/fields"
let BEHANCE_URL_INTERESTED_CREATIVE = "/creativestofollow"
let BEHANCE_URL_SEARCH_PROJECT = "/projects"
let BEHANCE_URL_PROJECT_INFO = "/projects"
